// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBykMBoAWjCNEI_lhtshWRIQeOuVSfHqhM',
    appId: '1:260156785531:web:289aab6584c5c2cf0973de',
    messagingSenderId: '260156785531',
    projectId: 'ieltstevapp',
    authDomain: 'ieltstevapp.firebaseapp.com',
    storageBucket: 'ieltstevapp.appspot.com',
    measurementId: 'G-8DLN05L7NR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw13VNBY7SypNYAk7ZvhYRqLsG7uzoQNM',
    appId: '1:260156785531:android:4bd659f38ef5626f0973de',
    messagingSenderId: '260156785531',
    projectId: 'ieltstevapp',
    storageBucket: 'ieltstevapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1AmRE1BsArXvAwCY5XysgODhWhmlwsiA',
    appId: '1:260156785531:ios:650f984df6ce11560973de',
    messagingSenderId: '260156785531',
    projectId: 'ieltstevapp',
    storageBucket: 'ieltstevapp.appspot.com',
    iosBundleId: 'com.example.ieltsTev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1AmRE1BsArXvAwCY5XysgODhWhmlwsiA',
    appId: '1:260156785531:ios:650f984df6ce11560973de',
    messagingSenderId: '260156785531',
    projectId: 'ieltstevapp',
    storageBucket: 'ieltstevapp.appspot.com',
    iosBundleId: 'com.example.ieltsTev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBykMBoAWjCNEI_lhtshWRIQeOuVSfHqhM',
    appId: '1:260156785531:web:acb28e08b6f352fd0973de',
    messagingSenderId: '260156785531',
    projectId: 'ieltstevapp',
    authDomain: 'ieltstevapp.firebaseapp.com',
    storageBucket: 'ieltstevapp.appspot.com',
    measurementId: 'G-QQ217RCS8B',
  );
}
